refactor: migrate to TypeScript
opengovsg/spcp-auth-client pull request #98
Opened 2020-11-13 01:50 UTC by mantariksh

Opening as a draft while I ask some questions about the types.

2020-11-13 02:14 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +  verifyJWT (jwtToken: string, callback: jwt.VerifyCallback): void {
strictly speaking this returns the returntype of the callback (see [library code](https://github.com/auth0/node-jsonwebtoken/blob/37650031fd0bac1a5b0d682bbfcf8c1705917aa9/verify.js#L216)), but I've left it as `void` rather than fight with `@types/jsonwebtoken`

2020-11-13 02:45 UTC, mantariksh reviewed
@LoneRifle hello! I've added some comments explaining my decisions and some of the weirder typecasting. I'd greatly appreciate your input if you know a better way to do it!

as you can probably tell, I tried to stick to adding types and avoid changing the logic as far as possible, because I'm not sure if you have the risk appetite for a more comprehensive rewrite. but let me know if you'd like to explore more comprehensive changes.

2020-11-13 02:45 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +  verifyJWT (jwtToken: string, callback: jwt.VerifyCallback): void {
strictly speaking this returns the returntype of the callback (see [library code](https://github.com/auth0/node-jsonwebtoken/blob/37650031fd0bac1a5b0d682bbfcf8c1705917aa9/verify.js#L216)), but I've left it as `void` rather than fight with `@types/jsonwebtoken`

2020-11-13 02:45 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +    verifier.keyInfoProvider = new KeyInfo(this.spcpCert) as unknown as xmlCrypto.FileKeyInfo
this casting was necessary because `getKey` in `xmlCrypto.FileKeyInfo` is supposed to return a `Buffer`, not `string`. I figured it would be safer to leave the return type as-is rather than change it do `Buffer.from`, plus the tests complained when I tried to change `getKey` to return `Buffer`.

2020-11-13 02:45 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +    const cpXMLBase64 = xpath.select('string(./*[local-name(.)=\'AttributeValue\'])', element) as unknown as string
so what I think is happening here is that `cpXMLBase64` is really a `string[]`, but `base64.decode` [converts it to a string](https://github.com/mathiasbynens/base64/blob/913b89753d99362855c71c02d04384d1d1a9c2fd/src/base64.js#L41). this casting is as close as I could get without declaring our own types for `base-64`.

2020-11-13 02:45 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +      const key = xpath.select('string(./@Name)', element) as unknown as string
I _think_ what's happening here is `key` is really a `string[]`, but it gets converted to a comma-delimited string when it is used as an object key. this casting is the closest way I could think of to represent this.

2020-11-13 05:17 UTC, LoneRifle requested changes
One other thing:
The `xxx.class.js` is a relic from the bad old days of JavaScript. I think TypeScript convention is to name classes as `xxx.ts`.

LGTM otherwise

2020-11-13 05:17 UTC, LoneRifle commented on src/SPCPAuthClient.class.ts
> +    const cpXMLBase64 = xpath.select('string(./*[local-name(.)=\'AttributeValue\'])', element) as unknown as string
I guess we really want a string, so how about...
```suggestion
    const cpXMLBase64 = xpath.select('string(./*[local-name(.)=\'AttributeValue\'])', element, true)!.toString()
```

2020-11-13 05:17 UTC, LoneRifle commented on src/SPCPAuthClient.class.ts
> +      const key = xpath.select('string(./@Name)', element) as unknown as string
I think we expect a single value for each element passed, so how about...
```suggestion
      const key = xpath.select('string(./@Name)', element, true)!.toString()
```

2020-11-13 05:17 UTC, LoneRifle commented on src/SPCPAuthClient.types.ts
> +export interface IConfig {
Avoid Hungarian notation, figure out an alternate naming scheme

2020-11-13 05:17 UTC, LoneRifle commented on src/SPCPAuthClient.class.ts
>     * @return {Boolean} sig0 - Boolean value of whether signatures in artifact response are verified
If you can spare the time, update the jsdoc

2020-11-13 05:17 UTC, LoneRifle commented on src/SPCPAuthClient.types.ts
> +export type ArtifactResolveWithErr = {
returning a response object which had either one thing or the other was perhaps one of my bigger mistakes in implementing this. We really should have gone with a `string | Error` kind of deal, or perhaps even be unafraid to actually throw Errors.

2020-11-13 05:32 UTC, LoneRifle commented on src/SPCPAuthClient.class.ts
> +    verifier.keyInfoProvider = new KeyInfo(this.spcpCert) as unknown as xmlCrypto.FileKeyInfo
So this is what I did:
```js
      getKey (): Buffer {
        return Buffer.from(this.key)
      }
```
ran the tests on gitpod, none are failing..

2020-11-16 03:39 UTC, mantariksh commented on src/SPCPAuthClient.class.ts
> +    verifier.keyInfoProvider = new KeyInfo(this.spcpCert) as unknown as xmlCrypto.FileKeyInfo
it works if you only make that change, but it breaks if you do `class KeyInfo extends xmlCrypto.FileKeyInfo`. I keep getting `ENAMETOOLONG`, which suggests that something upstream thinks that a file's contents are a filename. this means that we'd have to keep the `as unknown as xmlCrypto.FileKeyInfo`, regardless of whether we return a string or a Buffer from `getKey`.

Here's a sample error:
<img width="1343" alt="Screenshot 2020-11-16 at 12 43 06 AM" src="https://user-images.githubusercontent.com/29480346/99210226-3f2da880-2800-11eb-8f44-5e0a3cc179de.png">

2020-11-16 04:52 UTC, mantariksh commented on src/SPCPAuthClient.types.ts
> +export type ArtifactResolveWithErr = {
I've been trying to avoid changing the API, but do you want to make that change? If so we'd have to release a new major version, right?

2020-11-16 05:17 UTC, mantariksh commented
@LoneRifle just highlighting a major change I made since your last review: I adapted the types from `@types/jsonwebtoken` so we could return a more accurate type for `verifyJWT`. `@types/jsonwebtoken` enforced that the callback had to return `void`, but in reality the [library](https://github.com/auth0/node-jsonwebtoken/blob/37650031fd0bac1a5b0d682bbfcf8c1705917aa9/verify.js#L223) returns whatever the callback returns, so I gave the callback a generic type. See [this commit](https://github.com/opengovsg/spcp-auth-client/pull/98/commits/bdc07db07b775b32d85207b1fba717290cabfd5f) for the changes I made to the library types.

2020-11-16 08:24 UTC, LoneRifle commented on src/SPCPAuthClient.types.ts
> +export type ArtifactResolveWithErr = {
I don't, just making a record of my errors

2020-11-16 08:31 UTC, LoneRifle approved these changes
lgtm otherwise. Not sure if you think worth your while to send a patch to @DefinitelyTyped for the jsonwebtoken typings, so at your discretion.

2020-11-16 08:31 UTC, LoneRifle commented on src/SPCPAuthClient.types.ts
> +export type XpathNode = Parameters<XPathSelect>[1]
Surely it should be...
```suggestion
export type XPathNode = Parameters<XPathSelect>[1]
```

2020-11-16 09:30 UTC, merged